### ISSUE TITLE
Will Not Load 

### ISSUE THREAD

**Issue by OasisAvatar** [dev-hydrogen/Nightclub#4]
I'm using Minecraft Java 1.20.2, Paper 1.20.2 Build 291, Java 17, Nightclub version 2.3.1 on a locally hosted server. Not sure why. This is a first time install. 

[19:21:43 ERROR]: Error occurred while enabling Nightclub2.0 v2.3.1 (Is it up to date?)
java.lang.NoClassDefFoundError: team/unnamed/creative/sound/SoundRegistry
        at java.lang.Class.getDeclaredFields0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredFields(Class.java:3297) ~[?:?]
        at java.lang.Class.getDeclaredFields(Class.java:2371) ~[?:?]
        at dev.hypera.chameleon.core.Chameleon.<init>(Chameleon.java:61) ~[Nightclub-all-2.3.1.jar:?]
        at dev.hypera.chameleon.platforms.spigot.SpigotChameleon.<init>(SpigotChameleon.java:61) ~[Nightclub-all-2.3.1.jar:?]
        at exposed.hydrogen.nightclub.NightclubSpigot.onEnable(NightclubSpigot.java:36) ~[Nightclub-all-2.3.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-291]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-291]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-291]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-291]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.ClassNotFoundException: team.unnamed.creative.sound.SoundRegistry
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 18 more
[19:21:43 INFO]: [Nightclub2.0] Disabling Nightclub2.0 v2.3.1
[19:21:43 ERROR]: Error occurred (in the plugin loader) while disabling Nightclub2.0 v2.3.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "exposed.hydrogen.nightclub.light.LightUniverseManager.save()" because the return value of "exposed.hydrogen.nightclub.Nightclub.getLightUniverseManager()" is null
        at exposed.hydrogen.nightclub.NightclubSpigot.onDisable(NightclubSpigot.java:49) ~[Nightclub-all-2.3.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.2.jar:git-Paper-291]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.2.jar:git-Paper-291]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[paper-1.20.2.jar:git-Paper-291]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-291]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-291]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-291]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-291]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]

**Comment by OasisAvatar** [comment]
Issue looks to be I'm using 1.20.2 which is not supported.
